"""Add HistoriqueRole and Exposition.alertes cascade

Revision ID: 00ff39938e95
Revises: 40da25f13ce7
Create Date: 2026-08-24 12:16:39.210002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ff39938e95'
down_revision: Union[str, None] = '40da25f13ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
