"""Add HistoriqueRole and Exposition.alertes cascade

Revision ID: 40da25f13ce7
Revises: e876c6c31d5d
Create Date: 2026-08-24 12:14:09.697444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40da25f13ce7'
down_revision: Union[str, None] = 'e876c6c31d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historique_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_cible_id', sa.String(length=36), nullable=False),
    sa.Column('modifie_par_id', sa.String(length=36), nullable=False),
    sa.Column('ancien_role', sa.Enum('USER', 'SUPERVISOR', 'ADMIN', 'SUPER_ADMIN', name='roleutilisateur'), nullable=False),
    sa.Column('nouveau_role', sa.Enum('USER', 'SUPERVISOR', 'ADMIN', 'SUPER_ADMIN', name='roleutilisateur'), nullable=False),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_cible_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_roles')
    # ### end Alembic commands ###
