"""Add role field to User for privilege managent

Revision ID: 639fa41d006d
Revises: cd4eb80fae4a
Create Date: 2026-08-19 08:11:43.144682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639fa41d006d'
down_revision: Union[str, None] = 'cd4eb80fae4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'role',
            sa.Enum('USER', 'SUPERVISOR', 'ADMIN', 'SUPER_ADMIN', name='roleutilisateur'),
            nullable=False,
            server_default='USER',  # valeur SQL par defaut pour les lignes existantes
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
