"""Add ConfigurationSysteme table

Revision ID: 8b36f4127467
Revises: 2796e558c196
Create Date: 2026-08-19 14:47:23.529960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b36f4127467'
down_revision: Union[str, None] = '2796e558c196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_systeme',
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_systeme')
    # ### end Alembic commands ###
