"""Initial schema - Exposition, Source, Selecteur, JournalAudit

Revision ID: b98856fbd948
Revises: 
Create Date: 2026-08-07 12:14:05.946648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98856fbd948'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusions_faux_positifs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('ajoute_par', sa.String(length=255), nullable=False),
    sa.Column('date_ajout', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expositions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom_entite', sa.String(length=255), nullable=False),
    sa.Column('secteur_activite', sa.String(length=255), nullable=True),
    sa.Column('type_entite', sa.Enum('PUBLIQUE', 'PRIVEE', name='typeentite'), nullable=True),
    sa.Column('categorie_fuite', sa.Enum('CREDENTIALS', 'DONNEES_PERSONNELLES', 'DONNEES_FINANCIERES', 'DONNEES_SANTE', 'DOCUMENTS_INTERNES', 'CODE_SOURCE', 'NON_PRECISEE', name='categoriefuite'), nullable=False),
    sa.Column('date_premiere_detection', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_derniere_detection', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nombre_enregistrements_revendique', sa.Integer(), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=False),
    sa.Column('statut', sa.Enum('NEW', 'UNDER_REVIEW', 'CONFIRMED', 'FALSE_POSITIVE', 'NOTIFIED', 'CLOSED', name='statutexposition'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selecteurs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('valeur', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.Enum('DOMAINE', 'TELEPHONE', 'MINISTERE', 'AGENCE_GOUVERNEMENTALE', 'BANQUE', 'MICROFINANCE', 'TELECOM', 'UNIVERSITE', 'ENTREPRISE', 'VILLE_REGION', name='categorieselecteur'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('propose_par_ner', sa.Boolean(), nullable=False),
    sa.Column('valide_par_analyste', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type_source', sa.Enum('RANSOMWARE_SITE', 'PASTE', 'FORUM', 'TELEGRAM', 'TEST_CLAIRNET', name='typesource'), nullable=False),
    sa.Column('url_ou_identifiant', sa.String(length=500), nullable=False),
    sa.Column('derniere_collecte_reussie', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nombre_erreurs', sa.Integer(), nullable=False),
    sa.Column('temps_reponse_moyen', sa.Float(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('resultat', sa.Enum('SUCCES', 'ECHEC', name='resultataudit'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exposition_id', sa.String(length=36), nullable=False),
    sa.Column('type_source', sa.Enum('RANSOMWARE_SITE', 'PASTE', 'FORUM', 'TELEGRAM', 'TEST_CLAIRNET', name='typesource'), nullable=False),
    sa.Column('reference_source', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['exposition_id'], ['expositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_references')
    op.drop_table('journal_audit')
    op.drop_table('sources')
    op.drop_table('selecteurs')
    op.drop_table('expositions')
    op.drop_table('exclusions_faux_positifs')
    # ### end Alembic commands ###
