"""Add Alerte table for FR-25/FR-26

Revision ID: cd4eb80fae4a
Revises: 0eb711570cfd
Create Date: 2026-08-17 10:30:07.126429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4eb80fae4a'
down_revision: Union[str, None] = '0eb711570cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exposition_id', sa.String(length=36), nullable=False),
    sa.Column('canal', sa.Enum('EMAIL', 'SMS', 'WHATSAPP', 'INTERFACE', name='canalalerte'), nullable=False),
    sa.Column('statut_envoi', sa.Enum('EN_ATTENTE', 'ENVOYEE', 'ECHEC', name='statutenvoialerte'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_envoi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lue', sa.Boolean(), nullable=False),
    sa.Column('details_echec', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exposition_id'], ['expositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertes')
    # ### end Alembic commands ###
