"""Add ConfigurationSysteme table

Revision ID: e876c6c31d5d
Revises: 8b36f4127467
Create Date: 2026-08-19 14:56:39.506251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e876c6c31d5d'
down_revision: Union[str, None] = '8b36f4127467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
